### ISSUE TITLE
Should we split Bouldering from Sport Climbing?

### ISSUE THREAD

**Issue by auridevil** [auridevil/awesome_climbing#13]

**Comment by MattTwight** [comment]
We should because there are a world of videos on bouldering and I think it deserves a dedicated section.

**Comment by auridevil** [comment]
started working on it, if you find out things in movies that are bouldering only please open an issue.

Renamed alp in mountaneering, for mountain climbing and expeditions.

Trad will fit in movies or pitch, depending on video

**Comment by auridevil** [comment]
migrated all bouldering problem to new section.
